### PR TITLE
The ol' Wichita switcheroo

### PR DESCRIPTION
**Pull request by contolini**
Wichita Falls, TX and Wichita, KS had their data switched.

### CODE REVIEW

**Comment by marcesher** [comment]
@contolini Thanks! A few questions:

1. How was the data in this file generated, or was it all manual?
2. Is there a way to know if this is an isolated problem?

**Comment by contolini** [comment]
@marcesher 

1. I *think* @danny8000 got the data from some spreadsheets that were given to the HMDA team way back in the day. This JS file is currently manually maintained.
2. Not that I'm aware of. It might be possible to derive city names from the data points and check those names against the ones purported in this JS file buuuuuut the bang-to-buck ratio feels pretty low for that task. I'm hoping this is a one-off human error given the closeness of the cities' names.

**Comment by marcesher** [comment]
Thanks @contolini 

This also seems like something fairly easy to throw a browser test around

**Comment by higs4281** [comment]
this is not a one-off error. these cities also error out:

Springfield, IL --> sioux falls sd
Springfield, MA --> south bend-mishawaka IN-MI
Springfield, MO --> spartanburg, sc
Springfield, OH --> spokane, wa

the charts.min.js file has mixed CBSA codes.

CBSA44060:{name:"SPOKANE, WA",data:[[3455,3891,5016],[7410,10792,7934],[285,458,442]]}
CBSA44060:{name:"SPRINGFIELD, OH",data:[[39.3,43.9,50.4],[38,33.1,28],[8.6,11.3,10.1],[14.2,11.7,11.5]]},

**Comment by marcesher** [comment]
Thanks @higs4281 

Interestingly enough, the bottom chart works as expected in these handful of cases.

@contolini  What's the difference between the top and bottom?

**Comment by marcesher** [comment]
@contolini Please coordinate with whoever you need to

a) fix these
b) get browser tests written (see DEV-634 in Jira)

Ideally, don't pull Orlando in. This is a good opportunity for a newer dev to chip in and learn

**Comment by jessicarussell** [comment]
Wow, good catch.

For what it's worth, the Webinar is rescheduled for next Tuesday 4/14, so feel free to make changes between now and then. Also, I think @mehtadev17 helped coordinate the charts last summer, so he might have some insight on it while Seph is out.

**Comment by mehtadev17** [comment]
Yep, that would be me. I had to manually merge the old and new data in excel. Was hoping it was perfect but I know better. Thanks for solving this!

**Pull request merged**
