### PR TITLE
Update chart2.js

### PR DESCRIPTION
**Pull request by higs4281**
fixes out-of-sequence CBSAs

### CODE REVIEW

**Comment by contolini** [comment]
Thanks @higs4281! Do the same problems exist in chart1.js?

**Comment by higs4281** [comment]
@contolini there were four mismatches. fixed.

**Comment by contolini** [comment]
You da best.

**Comment by higs4281** [comment]
@contolini got it! 
the final pieces were the content files used to build the option choices for the two charts in index.html. once i got those aligned with the fixed data files, it all works.
we need a way to keep these files in sync for the next data refresh; 
also, isn't very dry to have two indentical chart dropdowns in content/homepage/charts/

**Comment by higs4281** [comment]
i wrote a [selenium test](https://gist.github.com/higs4281/0e025f3f3e04703f955c) to check every option in each table, and all choices pass.

**Comment by contolini** [comment]
:+1: :+1: :+1:

**Pull request merged**
