### PR TITLE
Add 2015 MSA Data

### PR DESCRIPTION
**Pull request by amymok**
## Additions:
- Added 2015 MSA Data

## Review:
@sleitner @sephcoster @JeffreyMFarley

### CODE REVIEW

**Comment by sleitner** [comment]
:+1:

**Comment by JeffreyMFarley** [comment]
Did we identify any _new_ MSA's this cycle that need to be tagged with `(2015)`?

**Comment by sleitner** [comment]
@JeffreyMFarley No, there were no MSA changes between 2014 and 2015 (and the extension of years is scripted). This is good to go, but it may break tests.

**Comment by sephcoster** [comment]
I don't expect to see any changes as the OMB updates were released mid 2015 so MSA designations should remain the same for 2014-2015 data. 👍

**Pull request merged**
